### ISSUE TITLE
payable address is broken in tronbox 2.5.1

### ISSUE THREAD

**Issue by metjm** [TRON-US/tronbox#15]
example: 

```    
function testSend(address payable to) public payable {
        to.transfer(msg.value);
    }
```

error: 
```
Error parsing /home/herpderp123.sol: ParsedContract.sol:62:31: P
    function testSend(address payable to) public payable {                                                
                              ^-----^                                                                     
```

**Comment by amovah** [comment]
I think `tronbox compile` and `tronbox migrate` use different solidity compiler version.

I ran `tronxbox compile` with bad solidity version and it's the log:

```bash
tronbox compile                                                                                                                                                                                             
Compiling ./contracts/Bet.sol...

/home/codeminer/test/contracts/Bet.sol:1:1: SyntaxError: Source file requires different compiler version (current compiler is 0.4.25+commit.69a1e720.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.6.23;
^----------------------^
```

and then I ran with this command, `tronbox migrate --reset --network shasta`, and it's the log:

```bash
tronbox migrate --reset --network shasta                                                                                                                                                                                    
(node:5461) V8: /home/codeminer/.npm/lib/node_modules/tronbox/build/cli.bundled.js:207958 Invalid asm.js: Invalid member of stdlib
Compiling ./contracts/Bet.sol...
Compiling ./contracts/Factory.sol...

/home/codeminer/workshop/tronel-contract/contracts/Bet.sol:3:1: 
ParserError: Source file requires different compiler version (current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)
```

as you can see, tronbox use two different solidity version. in `tronbox compile` it uses 0.4.25, and in `tronbox migrate --reset` it uses 0.5.4.

and there is another problem that is, payable address is broken, that's true.

Temporary Solution: first make your contract compatible with version 0.4.25 then compile contracts, `tronbox compile --compile-all`. then deploy contracts with this command, `tronbox migrate --network shasta`. at least it worked for me.

**Comment by shenyongri110** [comment]
@metjm @amovah We have a missing compiler version bug in tronbox, the fix is in pull request #16. We will merge and publish a new release after reviewing.

**Comment by amovah** [comment]
@shenyongri110 can we change compiler version now ?

and this #16 is going to fix which problem? two different compiler or payable address bug ?

**Comment by sullof** [comment]
@amovah @metjm 
I just published TronBox 2.5.2. Could you update and check if now it works, please?
If yes, can you close the issue? Thanks

**Comment by sullof** [comment]
Oops, the publishing failed. I am trying again.

**Comment by metjm** [comment]
yes, payable address worked. Awesome

**Comment by rori4** [comment]
I have the same issue. When I try to compile the contract it uses compiler 0.4.25
Tronbox v2.5.2

**Comment by ZetZer0** [comment]
Hi Metjm,

I have the old Tronwatch wallet, forgot/didn't to move my coins to another wallet. Now everything is gone, can you please help me? Am a bit desperate now.
