### ISSUE TITLE
Can't Compile Solidity ^0.5.4

### ISSUE THREAD

**Issue by rori4** [TRON-US/tronbox#18]
When I try to compile the contract it uses compiler 0.4.25
Tronbox v2.5.2

This is what I get when I try to run tronbox migrate:

```
tronbox migrate --reset
SyntaxError: Source file requires different compiler version 
(current compiler is 0.4.25+commit.69a1e720.Emscripten.clang - note that 
nightly builds are considered to be strictly less than the released version
pragma solidity ^0.5.4;
^---------------------^
ParserError: Source file requires different compiler version 
(current compiler is 0.5.4+commit.7b0de266.mod.Emscripten.clang)
```
Even if I try to use `pragma solidity >=0.4.23 <0.6.0;` in the compiled json file of the contract I get this:
```
  "compiler": {
    "name": "solc",
    "version": "0.4.25+commit.69a1e720.Emscripten.clang"
  },
```

 Might be related to #15

**Comment by rori4** [comment]
I found the solution so I hope this helps someone as it is not documented properly.
The compiler version MUST be specified in the `truffle.js` 
Like this:
```
module.exports = {
  networks: {
    useZeroFiveCompiler: true,
    development: {
     ...
    },
    mainnet: {
       ...
    },
shasta: {
      ...
    }
  }
};
```
If you want to use compiler 0.4.25 you should add `useZeroFourCompiler: true` and remove useZeroFiveCompiler

By default it seems that tronbox uses 0.4.25 which is unexpected behavior IMO.

**Comment by sullof** [comment]
@rori4 TronBox chooses the version based on the version of JavaTron installed on the network you are connected to. If that is 3.5 — which does not support solidity 0.5.4 — it defaults to 0.4.25.
