### ISSUE TITLE
Sending TRX to payable function not working

### ISSUE THREAD

**Issue by kleoken** [TRON-US/tronbox#27]
I have a payable function defined here:
```
  function placeBet(uint256 amount) external payable returns (address) {
    // make sure the amount we want to send is the amount we actually sent
    require(amount == msg.value);
    currentPot += amount;
    currentLeader = msg.sender;
    // return the current leader
    return currentLeader;
  }
```

In my tronbox tests I call it like this:
```
  await game.placeBet(300000000, {from: accounts[1], callValue: 300000000})
  let leader2 = await game.currentLeader()

  // ensure the lead changed
  assert(leader1 != leader2, "Bet was insufficient to update leader")
```
The assert is passing and I checked manually currentLeader data is being updated. However, when I look at the balance of the contract with tronbox `await tronWeb.trx.getBalance(contract)` it returns 0 and when using `http://127.0.0.1:9090/admin/accounts` (from tronquickstart) barely any TRX (less than 1) is being taken from `accounts[1]`. 

Why is data changing but no TRX being sent?

**Comment by sullof** [comment]
I think this has been fixed in a following version of TronWeb.
